### ISSUE TITLE
No glossary at the end of document

### ISSUE THREAD

**Issue by abforce** [momeni/sharif-thesis#1]
I've been using your template for writing my master thesis. When I compile the `main.tex` file, it's compiled fine with no errors. Regarding the spec, there should be two glossaries at the end of the generated PDF document (i.e. English to Persian and vice versa), but there aren't such glossaries.

It's worth mentioning that the `\نوواژه` and `\واژه` commands have been used properly and even we've got footnotes (so, this assures us those commands are fine). However the main glossaries aren't generated.

Could you please take a look and let me know what's going on? Or just am I missing something?

**Comment by momeni** [comment]
Did you use the **make** command for compilation? If yes, paste the resulting error logs here.
You must have **xindy** installed (it is used by the Makefile to generate the glossaries).

**Comment by abforce** [comment]
Thanks for your prompt response.

> Did you use the make command for compilation?

Yes, I did.

> If yes, paste the resulting error logs here.

```
xindy --language persian --codepage utf8 --input-markup xindy --module main --log-file main.fa.glg --out-file main.fa.gls main.fa.glo
Cannot locate xindy module for language persian in codepage utf8.
Makefile:51: recipe for target 'main.pdf' failed
```

After narrowing down the problem, I just surprisingly figured out that there isn't a directory called Persian in my `/usr/share/xindy/lang`. I also cross posted the problem on [TeX Stack Exchange](http://tex.stackexchange.com/questions/321727/no-persian-language-in-xindy-lang-directory).

May I ask you on which OS have you managed to compile the document? (by the way, I'm using Ubuntu 16.04 LTS)

**Comment by abforce** [comment]
_cross posted from http://tex.stackexchange.com/questions/321727/no-persian-language-in-xindy-lang-directory#comment-786626 for helping future readers_

>  As [Paul Gaborit](http://tex.stackexchange.com/users/14500/paul-gaborit) mentioned in [his comment](http://tex.stackexchange.com/questions/321727/no-persian-language-in-xindy-lang-directory#comment-786626), `xindy` of Ubuntu repositories is not the latest version and should be updated to resolve the issue.
> 
> The following repo contains the latest version, so you should first add the following line to your `/etc/apt/sources.list` and then update `xindy` and `xindy-rules`.
> 
> ```
> deb http://ftp.de.debian.org/debian sid main 
> ```
> 
> Once you're done, you can safely remove this repo from the sources file.
> 
> P.S: [Mirrors](https://packages.debian.org/sid/all/xindy-rules/download) are also available.

**Comment by maryammsd** [comment]
The other solution is posted [here](http://qa.parsilatex.com/37739/%D8%B9%D8%AF%D9%85-%D8%A7%D8%AC%D8%B1%D8%A7%DB%8C-%D8%B4%D8%AF%D9%86-xindy-%D9%88-%D8%AE%D8%B1%D9%88%D8%AC%DB%8C-%D9%86%D8%AF%D8%A7%D8%AF%D9%86-%D9%88%D8%A7%DA%98%D9%87-%D9%86%D8%A7%D9%85%D9%87) for your reference.
