### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by mohammad7t** [momeni/sharif-thesis#2]
Would you please add a note in the documentation, on how to acquire fonts like `Yas` which is used in this project?

Thanks a lot

**Comment by momeni** [comment]
On ArchLinux, you can install the Yas font using [this](https://aur.archlinux.org/packages/ttf-yas/) package.
Elsewhere, you can download the font itself from [here](https://fontlibrary.org/en/font/yas).

**Comment by SinRas** [comment]
@momeni 
Could you add `fonts` folder and add all the required fonts there in the project for _completeness_?
