### ISSUE TITLE
Fix the tableofcontents to work with the toc=indented instead of the toc=flat mode

### ISSUE THREAD

**Issue by momeni** [momeni/sharif-thesis#6]
The \tableofcontents should be rendered with the toc=indented class option, but this option shifts sections rightward due to some incompatibility. Sections should be shifted leftward.
As a temporary fix, chapter entries are shifted even more rightward.

**Comment by ghost** [comment]
If this is xepersian's issue (and not your own template), then please make a bug report and I will fix it.

bidi: https://github.com/vafa/bidi/issues
xepersian: https://github.com/vafa/xepersian/issues
